# Generated by Django 4.0.4 on 2022-05-06 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NhaCungCap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenNCC', models.CharField(max_length=200)),
                ('diaChi', models.TextField(max_length=500)),
                ('dienTHoai', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PhieuNhapKho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngayNhap', models.DateTimeField()),
                ('maNV', models.CharField(max_length=200)),
                ('maNCC', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supply.nhacungcap')),
            ],
        ),
        migrations.CreateModel(
            name='ChiTietPhieuNhap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soLuong', models.IntegerField()),
                ('donGia', models.FloatField()),
                ('thanhTien', models.FloatField()),
                ('maPNK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supply.phieunhapkho')),
                ('maSP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.sanpham')),
            ],
        ),
    ]
