# Generated by Django 4.0.4 on 2022-05-06 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonDatHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngayDat', models.DateTimeField()),
                ('ngayGiao', models.DateTimeField()),
                ('maKH', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.khachhang')),
            ],
        ),
        migrations.CreateModel(
            name='ChiTietDonDH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soLuong', models.IntegerField()),
                ('donGia', models.FloatField()),
                ('thanhTien', models.FloatField()),
                ('maDDH', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.dondathang')),
                ('maSP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.sanpham')),
            ],
        ),
    ]
