# Generated by Django 4.0.4 on 2022-05-04 15:16

from django.db import migrations, models
import django.db.models.deletion
import products.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HangSX',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenHSX', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SanPham',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenSP', models.CharField(max_length=200)),
                ('soLuong', models.IntegerField()),
                ('anhSP', models.ImageField(blank=True, null=True, upload_to=products.models.get_file_path)),
                ('moTa', models.TextField(max_length=500)),
                ('kieuDang', models.CharField(max_length=200)),
                ('manHinh', models.CharField(max_length=200)),
                ('camera', models.CharField(max_length=200)),
                ('boNhoTrong', models.CharField(max_length=200)),
                ('heDieuHanh', models.CharField(max_length=200)),
                ('CPU', models.CharField(max_length=200)),
                ('maHSX', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.hangsx')),
            ],
        ),
    ]
