# Generated by Django 4.0.4 on 2022-05-07 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sanpham',
            name='pin',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sanpham',
            name='ram',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
